const char *courseNames[] =
{
    "Figure-8 Circuit",
    "Yoshi Falls",
    "Cheep Cheep Beach",
    "Luigi's Mansion",
    "Desert Hills",
    "Delfino Square",
    "Waluigi Pinball",
    "Shroom Ridge",
    "DK Pass",
    "Tick-Tock Clock",
    "Mario Circuit",
    "Airship Fortress",
    "Wario Stadium",
    "Peach Gardens",
    "Bowser Castle",
    "Rainbow Road",
    "SNES Mario Circuit 1",
    "N64 Moo Moo Farm",
    "GBA Peach Circuit",
    "GCN Luigi Circuit",
    "SNES Donut Plains 1",
    "N64 Frappe Snowland",
    "GBA Bowser Castle 2",
    "GCN Baby Park",
    "SNES Koopa Beach 2",
    "N64 Choco Mountain",
    "GBA Luigi Circuit",
    "GCN Mushroom Bridge",
    "SNES Choco Island 2",
    "N64 Banshee Boardwalk",
    "GBA Sky Garden",
    "GCN Yoshi Circuit"
};

const char *characterNames[] =
{
    "Mario",
    "Donkey Kong",
    "Toad",
    "Bowser",
    "Peach",
    "Wario",
    "Yoshi",
    "Luigi",
    "Dry Bones",
    "Daisy",
    "Waluigi",
    "R.O.B.",
    "Shy Guy"
};

const char *kartNames[] =
{
    "Standard MR",
    "Shooting Star",
    "B Dasher",
    "Standard DK",
    "Wildlife",
    "Ranbi Rider",
    "Standard TD",
    "Mushmellow",
    "4-Wheel Cradle",
    "Standard BW",
    "Hurricane",
    "Tyrant",
    "Standard PC",
    "Light Tripper",
    "Royale",
    "Standard WR",
    "Brute",
    "Dragonfly",
    "Standard YS",
    "Egg 1",
    "Cucumber",
    "Standard LG",
    "Poltergust 4000",
    "Streamliner",
    "Standard DB",
    "Dry Bomber",
    "Banisher",
    "Standard DS",
    "Light Dancer",
    "Power Flower",
    "Standard WL",
    "Gold Mantis",
    "Zipper",
    "Standard RB",
    "ROB-BLS",
    "ROB-LGS",
    "Standard SG"
};